In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data_siswa = pd.DataFrame(
    [
        ['Ridho', 173, 73, "M"],
        ['Rudy', 178, 75, "M"],
        ['Cindy', 170, 54, "F"]
    ], columns=['Nama', 'Tinggi', 'Berat', 'Jenis Kelamin']
)
data_siswa

    Nama  Tinggi  Berat Jenis Kelamin
0  Ridho     173     73             M
1   Rudy     178     75             M
2  Cindy     170     54             F

In [ ]:
data= np.array([
        ['Ridho', 173, 73, "M"],
        ['Rudy', 178, 75, "M"],
        ['Cindy', 170, 54, "F"]
    ])
data

array([['Ridho', '173', '73', 'M'],
       ['Rudy', '178', '75', 'M'],
       ['Cindy', '170', '54', 'F']], dtype='<U21')

In [ ]:
data.shape

(3, 4)

In [ ]:
data_siswa2 = pd.DataFrame(
      {
          "Nama": ["Ridho", "Rudy", "Cindy"],
          "Tinggi": [173, 178, 170],
          "Berat": [73, 75, 54],
          "Jenis Kelamin": ["M", "M", "F"]
      }
)
data_siswa2

    Nama  Tinggi  Berat Jenis Kelamin
0  Ridho     173     73             M
1   Rudy     178     75             M
2  Cindy     170     54             F

In [ ]:
df = pd.read_excel("/content/sample_data/SuperStore.xlsx")
df

,Order_ID,Customer_ID,Postal_Code,Product_ID,Sales,Quantity,Discount,Profit,Category,Sub-Category,Product_Name,Order_Date,Ship_Date,Ship_Mode,Customer_Name,Segment,Country/Region,City,State,Region
0,CA-2019-152156,CG-12520,42420,FUR-BO-10001798,261.9600,2,0.00,41.9136,Furniture,Bookcases,Bush Somerset Collection Bookcase,2019-11-08,2019-11-11,Second Class,Claire Gute,Consumer,United States,Henderson,Kentucky,South
1,CA-2019-152156,CG-12520,42420,FUR-CH-10000454,731.9400,3,0.00,219.5820,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",2019-11-08,2019-11-11,Second Class,Claire Gute,Consumer,United States,Henderson,Kentucky,South
2,CA-2019-138688,DV-13045,90036,OFF-LA-10000240,14.6200,2,0.00,6.8714,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,2019-06-12,2019-06-16,Second Class,Darrin Van Huff,Corporate,United States,Los Angeles,California,West
3,US-2018-108966,SO-20335,33311,FUR-TA-10000577,957.5775,5,0.45,-383.0310,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,2018-10-11,2018-10-18,Standard Class,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,South
4,US-2018-108966,SO-20335,33311,OFF-ST-10000760,22.3680,2,0.20,2.5164,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,2018-10-11,2018-10-18,Standard Class,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,South
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,CA-2017-110422,TB-21400,33180,FUR-FU-10001889,25.2480,3,0.20,4.1028,Furniture,Furnishings,Ultra Door Pull Handle,2017-01-21,2017-01-23,Second Class,Tom Boeckenhauer,Consumer,United States,Miami,Florida,South
9990,CA-2020-121258,DB-13060,92627,FUR-FU-10000747,91.9600,2,0.00,15.6332,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,2020-02-26,2020-03-03,Standard Class,Dave Brooks,Consumer,United States,Costa Mesa,California,West
9991,CA-2020-121258,DB-13060,92627,TEC-PH-10003645,258.5760,2,0.20,19.3932,Technology,Phones,Aastra 57i VoIP phone,2020-02-26,2020-03-03,Standard Class,Dave Brooks,Consumer,United States,Costa Mesa,California,West
9992,CA-2020-121258,DB-13060,92627,OFF-PA-10004041,29.6000,4,0.00,13.3200,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",2020-02-26,2020-03-03,Standard Class,Dave Brooks,Consumer,United States,Costa Mesa,California,West
9993,CA-2020-119914,CC-12220,92683,OFF-AP-10002684,243.1600,2,0.00,72.9480,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",2020-05-04,2020-05-09,Second Class,Chris Cortes,Consumer,United States,Westminster,California,West

In [ ]:
df.head(10)

,Order_ID,Customer_ID,Postal_Code,Product_ID,Sales,Quantity,Discount,Profit,Category,Sub-Category,Product_Name,Order_Date,Ship_Date,Ship_Mode,Customer_Name,Segment,Country/Region,City,State,Region
0,CA-2019-152156,CG-12520,42420,FUR-BO-10001798,261.9600,2,0.00,41.9136,Furniture,Bookcases,Bush Somerset Collection Bookcase,2019-11-08,2019-11-11,Second Class,Claire Gute,Consumer,United States,Henderson,Kentucky,South
1,CA-2019-152156,CG-12520,42420,FUR-CH-10000454,731.9400,3,0.00,219.5820,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",2019-11-08,2019-11-11,Second Class,Claire Gute,Consumer,United States,Henderson,Kentucky,South
2,CA-2019-138688,DV-13045,90036,OFF-LA-10000240,14.6200,2,0.00,6.8714,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,2019-06-12,2019-06-16,Second Class,Darrin Van Huff,Corporate,United States,Los Angeles,California,West
3,US-2018-108966,SO-20335,33311,FUR-TA-10000577,957.5775,5,0.45,-383.0310,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,2018-10-11,2018-10-18,Standard Class,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,South
4,US-2018-108966,SO-20335,33311,OFF-ST-10000760,22.3680,2,0.20,2.5164,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,2018-10-11,2018-10-18,Standard Class,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,South
5,CA-2017-115812,BH-11710,90032,FUR-FU-10001487,48.8600,7,0.00,14.1694,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,2017-06-09,2017-06-14,Standard Class,Brosina Hoffman,Consumer,United States,Los Angeles,California,West
6,CA-2017-115812,BH-11710,90032,OFF-AR-10002833,7.2800,4,0.00,1.9656,Office Supplies,Art,Newell 322,2017-06-09,2017-06-14,Standard Class,Brosina Hoffman,Consumer,United States,Los Angeles,California,West
7,CA-2017-115812,BH-11710,90032,TEC-PH-10002275,907.1520,6,0.20,90.7152,Technology,Phones,Mitel 5320 IP Phone VoIP phone,2017-06-09,2017-06-14,Standard Class,Brosina Hoffman,Consumer,United States,Los Angeles,California,West
8,CA-2017-115812,BH-11710,90032,OFF-BI-10003910,18.5040,3,0.20,5.7825,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,2017-06-09,2017-06-14,Standard Class,Brosina Hoffman,Consumer,United States,Los Angeles,California,West
9,CA-2017-115812,BH-11710,90032,OFF-AP-10002892,114.9000,5,0.00,34.4700,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,2017-06-09,2017-06-14,Standard Class,Brosina Hoffman,Consumer,United States,Los Angeles,California,West

In [ ]:
df.tail(10)

,Order_ID,Customer_ID,Postal_Code,Product_ID,Sales,Quantity,Discount,Profit,Category,Sub-Category,Product_Name,Order_Date,Ship_Date,Ship_Mode,Customer_Name,Segment,Country/Region,City,State,Region
9984,CA-2018-100251,DV-13465,11561,OFF-LA-10003766,31.500,10,0.0,15.1200,Office Supplies,Labels,Self-Adhesive Removable Labels,2018-05-17,2018-05-23,Standard Class,Dianna Vittorini,Consumer,United States,Long Beach,New York,East
9985,CA-2018-100251,DV-13465,11561,OFF-SU-10000898,55.600,4,0.0,16.1240,Office Supplies,Supplies,Acme Hot Forged Carbon Steel Scissors with Nic...,2018-05-17,2018-05-23,Standard Class,Dianna Vittorini,Consumer,United States,Long Beach,New York,East
9986,CA-2019-125794,ML-17410,90008,TEC-AC-10003399,36.240,1,0.0,15.2208,Technology,Accessories,Memorex Mini Travel Drive 64 GB USB 2.0 Flash ...,2019-09-29,2019-10-03,Standard Class,Maris LaWare,Consumer,United States,Los Angeles,California,West
9987,CA-2020-163629,RA-19885,30605,TEC-AC-10001539,79.990,1,0.0,28.7964,Technology,Accessories,Logitech G430 Surround Sound Gaming Headset wi...,2020-11-17,2020-11-21,Standard Class,Ruben Ausman,Corporate,United States,Athens,Georgia,South
9988,CA-2020-163629,RA-19885,30605,TEC-PH-10004006,206.100,5,0.0,55.6470,Technology,Phones,Panasonic KX - TS880B Telephone,2020-11-17,2020-11-21,Standard Class,Ruben Ausman,Corporate,United States,Athens,Georgia,South
9989,CA-2017-110422,TB-21400,33180,FUR-FU-10001889,25.248,3,0.2,4.1028,Furniture,Furnishings,Ultra Door Pull Handle,2017-01-21,2017-01-23,Second Class,Tom Boeckenhauer,Consumer,United States,Miami,Florida,South
9990,CA-2020-121258,DB-13060,92627,FUR-FU-10000747,91.960,2,0.0,15.6332,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,2020-02-26,2020-03-03,Standard Class,Dave Brooks,Consumer,United States,Costa Mesa,California,West
9991,CA-2020-121258,DB-13060,92627,TEC-PH-10003645,258.576,2,0.2,19.3932,Technology,Phones,Aastra 57i VoIP phone,2020-02-26,2020-03-03,Standard Class,Dave Brooks,Consumer,United States,Costa Mesa,California,West
9992,CA-2020-121258,DB-13060,92627,OFF-PA-10004041,29.600,4,0.0,13.3200,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",2020-02-26,2020-03-03,Standard Class,Dave Brooks,Consumer,United States,Costa Mesa,California,West
9993,CA-2020-119914,CC-12220,92683,OFF-AP-10002684,243.160,2,0.0,72.9480,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",2020-05-04,2020-05-09,Second Class,Chris Cortes,Consumer,United States,Westminster,California,West

# Mengubah tipe data

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        9994 non-null   object
 1   Customer_ID     9994 non-null   object
 2   Postal_Code     9994 non-null   int64
 3   Product_ID      9994 non-null   object
 4   Sales           9994 non-null   float64
 5   Quantity        9994 non-null   int64
 6   Discount        9994 non-null   float64
 7   Profit          9994 non-null   float64
 8   Category        9994 non-null   object
 9   Sub-Category    9994 non-null   object
 10  Product_Name    9994 non-null   object
 11  Order_Date      9994 non-null   datetime64[ns]
 12  Ship_Date       9994 non-null   datetime64[ns]
 13  Ship_Mode       9994 non-null   object
 14  Customer_Name   9994 non-null   object
 15  Segment         9994 non-null   object
 16  Country/Region  9994 non-null   object
 17  City            9994 non-null   object
 18  State           9994 non-null   object
 19  Region          9994 non-null   object
dtypes: datetime64[ns](2), float64(3), int64(2), object(13)
memory usage: 1.5+ MB

In [ ]:
df['Postal_Code'] = df['Postal_Code'].astype('category')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        9994 non-null   object
 1   Customer_ID     9994 non-null   object
 2   Postal_Code     9994 non-null   category
 3   Product_ID      9994 non-null   object
 4   Sales           9994 non-null   float64
 5   Quantity        9994 non-null   int64
 6   Discount        9994 non-null   float64
 7   Profit          9994 non-null   float64
 8   Category        9994 non-null   object
 9   Sub-Category    9994 non-null   object
 10  Product_Name    9994 non-null   object
 11  Order_Date      9994 non-null   datetime64[ns]
 12  Ship_Date       9994 non-null   datetime64[ns]
 13  Ship_Mode       9994 non-null   object
 14  Customer_Name   9994 non-null   object
 15  Segment         9994 non-null   object
 16  Country/Region  9994 non-null   object
 17  City            9994 non-null   object
 18  State           9994 non-null   object
 19  Region          9994 non-null   object
dtypes: category(1), datetime64[ns](2), float64(3), int64(1), object(13)
memory usage: 1.5+ MB

In [ ]:
test1 = df[['Postal_Code', 'Sales', 'Quantity']].copy()
test2 = test1.copy()

In [ ]:
test1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Postal_Code  9994 non-null   category
 1   Sales        9994 non-null   float64
 2   Quantity     9994 non-null   int64
dtypes: category(1), float64(1), int64(1)
memory usage: 196.9 KB

In [ ]:
test2['Postal_Code'] = test2['Postal_Code'].astype('object')
test2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Postal_Code  9994 non-null   object
 1   Sales        9994 non-null   float64
 2   Quantity     9994 non-null   int64
dtypes: float64(1), int64(1), object(1)
memory usage: 234.4+ KB

# Menampilkan List Columns dan Mengubah Tampilan nama kolom

In [ ]:
df.columns

Index(['Order_ID', 'Customer_ID', 'Postal_Code', 'Product_ID', 'Sales',
       'Quantity', 'Discount', 'Profit', 'Category', 'Sub-Category',
       'Product_Name', 'Order_Date', 'Ship_Date', 'Ship_Mode', 'Customer_Name',
       'Segment', 'Country/Region', 'City', 'State', 'Region'],
      dtype='object')

In [ ]:
df.columns = df.columns.str.lower()
df.columns

Index(['order_id', 'customer_id', 'postal_code', 'product_id', 'sales',
       'quantity', 'discount', 'profit', 'category', 'sub-category',
       'product_name', 'order_date', 'ship_date', 'ship_mode', 'customer_name',
       'segment', 'country/region', 'city', 'state', 'region'],
      dtype='object')

# Column Slicing

In [ ]:
type(df['order_id'])

pandas.core.series.Series

In [ ]:
type(df[['order_id', 'sales', 'quantity']])

pandas.core.frame.DataFrame

# df.loc vs df.iloc

In [ ]:
#  loc[baris, kolom]
df.loc[:10, ['order_id', 'sales', 'quantity']]

          order_id      sales  quantity
0   CA-2019-152156   261.9600         2
1   CA-2019-152156   731.9400         3
2   CA-2019-138688    14.6200         2
3   US-2018-108966   957.5775         5
4   US-2018-108966    22.3680         2
5   CA-2017-115812    48.8600         7
6   CA-2017-115812     7.2800         4
7   CA-2017-115812   907.1520         6
8   CA-2017-115812    18.5040         3
9   CA-2017-115812   114.9000         5
10  CA-2017-115812  1706.1840         9

In [ ]:
#  iloc[baris(index), kolom(index)]
df.iloc[:10, [0, 2, 3]]

         order_id postal_code       product_id
0  CA-2019-152156       42420  FUR-BO-10001798
1  CA-2019-152156       42420  FUR-CH-10000454
2  CA-2019-138688       90036  OFF-LA-10000240
3  US-2018-108966       33311  FUR-TA-10000577
4  US-2018-108966       33311  OFF-ST-10000760
5  CA-2017-115812       90032  FUR-FU-10001487
6  CA-2017-115812       90032  OFF-AR-10002833
7  CA-2017-115812       90032  TEC-PH-10002275
8  CA-2017-115812       90032  OFF-BI-10003910
9  CA-2017-115812       90032  OFF-AP-10002892

# Filtering (Coditional Statement)

## Classic Style

In [ ]:
df[df['sales'] > 500].head()

,order_id,customer_id,postal_code,product_id,sales,quantity,discount,profit,category,sub-category,product_name,order_date,ship_date,ship_mode,customer_name,segment,country/region,city,state,region
1,CA-2019-152156,CG-12520,42420,FUR-CH-10000454,731.9400,3,0.00,219.5820,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",2019-11-08,2019-11-11,Second Class,Claire Gute,Consumer,United States,Henderson,Kentucky,South
3,US-2018-108966,SO-20335,33311,FUR-TA-10000577,957.5775,5,0.45,-383.0310,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,2018-10-11,2018-10-18,Standard Class,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,South
7,CA-2017-115812,BH-11710,90032,TEC-PH-10002275,907.1520,6,0.20,90.7152,Technology,Phones,Mitel 5320 IP Phone VoIP phone,2017-06-09,2017-06-14,Standard Class,Brosina Hoffman,Consumer,United States,Los Angeles,California,West
10,CA-2017-115812,BH-11710,90032,FUR-TA-10001539,1706.1840,9,0.20,85.3092,Furniture,Tables,Chromcraft Rectangular Conference Tables,2017-06-09,2017-06-14,Standard Class,Brosina Hoffman,Consumer,United States,Los Angeles,California,West
11,CA-2017-115812,BH-11710,90032,TEC-PH-10002033,911.4240,4,0.20,68.3568,Technology,Phones,Konftel 250 Conference phone - Charcoal black,2017-06-09,2017-06-14,Standard Class,Brosina Hoffman,Consumer,United States,Los Angeles,California,West

## Query Style

`pandas.read_sql(sql, con, index_col=None, coerce_float=True, params=None, parse_dates=None, columns=None, chunksize=None, dtype_backend=<no_default>, dtype=None)`

In [ ]:
# Query
df.query('sales > 500').head()

,order_id,customer_id,postal_code,product_id,sales,quantity,discount,profit,category,sub-category,product_name,order_date,ship_date,ship_mode,customer_name,segment,country/region,city,state,region
1,CA-2019-152156,CG-12520,42420,FUR-CH-10000454,731.9400,3,0.00,219.5820,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",2019-11-08,2019-11-11,Second Class,Claire Gute,Consumer,United States,Henderson,Kentucky,South
3,US-2018-108966,SO-20335,33311,FUR-TA-10000577,957.5775,5,0.45,-383.0310,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,2018-10-11,2018-10-18,Standard Class,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,South
7,CA-2017-115812,BH-11710,90032,TEC-PH-10002275,907.1520,6,0.20,90.7152,Technology,Phones,Mitel 5320 IP Phone VoIP phone,2017-06-09,2017-06-14,Standard Class,Brosina Hoffman,Consumer,United States,Los Angeles,California,West
10,CA-2017-115812,BH-11710,90032,FUR-TA-10001539,1706.1840,9,0.20,85.3092,Furniture,Tables,Chromcraft Rectangular Conference Tables,2017-06-09,2017-06-14,Standard Class,Brosina Hoffman,Consumer,United States,Los Angeles,California,West
11,CA-2017-115812,BH-11710,90032,TEC-PH-10002033,911.4240,4,0.20,68.3568,Technology,Phones,Konftel 250 Conference phone - Charcoal black,2017-06-09,2017-06-14,Standard Class,Brosina Hoffman,Consumer,United States,Los Angeles,California,West

## Multiple Conditions

In [ ]:
# memfilter dengan dua atau lebih kondisi
# ingat: untuk menghindari kesalahan penulisan ekspresi, gunakan tanda kurung

# gunakan bitwise operator
# & untuk and
# | untuk or
# ~ untuk not

# memfilter transaksi dengan sales > 100 dari kategori Furniture

df[(df['sales'] > 500) & (df['quantity'] > 10)].head()

,order_id,customer_id,postal_code,product_id,sales,quantity,discount,profit,category,sub-category,product_name,order_date,ship_date,ship_mode,customer_name,segment,country/region,city,state,region
251,CA-2019-145625,KC-16540,92037,TEC-AC-10003832,3347.370,13,0.00,636.0003,Technology,Accessories,Logitech P710e Mobile Speakerphone,2019-09-11,2019-09-17,Standard Class,Kelly Collister,Consumer,United States,San Diego,California,West
412,CA-2020-117457,KH-16510,94110,FUR-BO-10001972,1336.829,13,0.15,31.4548,Furniture,Bookcases,O'Sullivan 4-Shelf Bookcase in Odessa Pine,2020-12-08,2020-12-12,Standard Class,Keith Herrera,Consumer,United States,San Francisco,California,West
660,CA-2018-146563,CB-12025,76017,OFF-ST-10001511,724.080,14,0.20,-135.7650,Office Supplies,Storage,Space Solutions Commercial Steel Shelving,2018-08-24,2018-08-28,Standard Class,Cassandra Brandow,Consumer,United States,Arlington,Texas,Central
949,US-2020-110576,RB-19795,19120,FUR-TA-10004154,2065.320,12,0.40,-619.5960,Furniture,Tables,"Riverside Furniture Oval Coffee Table, Oval En...",2020-11-28,2020-12-02,Standard Class,Ross Baird,Home Office,United States,Philadelphia,Pennsylvania,East
1013,US-2018-126214,JS-15880,98103,FUR-TA-10003748,1618.370,13,0.00,356.0414,Furniture,Tables,Bevis 36 x 72 Conference Tables,2018-12-21,2018-12-24,Second Class,John Stevenson,Consumer,United States,Seattle,Washington,West

In [ ]:
df.query('sales > 500 & quantity > 10').head()

,order_id,customer_id,postal_code,product_id,sales,quantity,discount,profit,category,sub-category,product_name,order_date,ship_date,ship_mode,customer_name,segment,country/region,city,state,region
251,CA-2019-145625,KC-16540,92037,TEC-AC-10003832,3347.370,13,0.00,636.0003,Technology,Accessories,Logitech P710e Mobile Speakerphone,2019-09-11,2019-09-17,Standard Class,Kelly Collister,Consumer,United States,San Diego,California,West
412,CA-2020-117457,KH-16510,94110,FUR-BO-10001972,1336.829,13,0.15,31.4548,Furniture,Bookcases,O'Sullivan 4-Shelf Bookcase in Odessa Pine,2020-12-08,2020-12-12,Standard Class,Keith Herrera,Consumer,United States,San Francisco,California,West
660,CA-2018-146563,CB-12025,76017,OFF-ST-10001511,724.080,14,0.20,-135.7650,Office Supplies,Storage,Space Solutions Commercial Steel Shelving,2018-08-24,2018-08-28,Standard Class,Cassandra Brandow,Consumer,United States,Arlington,Texas,Central
949,US-2020-110576,RB-19795,19120,FUR-TA-10004154,2065.320,12,0.40,-619.5960,Furniture,Tables,"Riverside Furniture Oval Coffee Table, Oval En...",2020-11-28,2020-12-02,Standard Class,Ross Baird,Home Office,United States,Philadelphia,Pennsylvania,East
1013,US-2018-126214,JS-15880,98103,FUR-TA-10003748,1618.370,13,0.00,356.0414,Furniture,Tables,Bevis 36 x 72 Conference Tables,2018-12-21,2018-12-24,Second Class,John Stevenson,Consumer,United States,Seattle,Washington,West

# ~ (Not)

In [ ]:
df[~(df['category'] == 'Furniture')].head()

,order_id,customer_id,postal_code,product_id,sales,quantity,discount,profit,category,sub-category,product_name,order_date,ship_date,ship_mode,customer_name,segment,country/region,city,state,region
2,CA-2019-138688,DV-13045,90036,OFF-LA-10000240,14.620,2,0.0,6.8714,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,2019-06-12,2019-06-16,Second Class,Darrin Van Huff,Corporate,United States,Los Angeles,California,West
4,US-2018-108966,SO-20335,33311,OFF-ST-10000760,22.368,2,0.2,2.5164,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,2018-10-11,2018-10-18,Standard Class,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,South
6,CA-2017-115812,BH-11710,90032,OFF-AR-10002833,7.280,4,0.0,1.9656,Office Supplies,Art,Newell 322,2017-06-09,2017-06-14,Standard Class,Brosina Hoffman,Consumer,United States,Los Angeles,California,West
7,CA-2017-115812,BH-11710,90032,TEC-PH-10002275,907.152,6,0.2,90.7152,Technology,Phones,Mitel 5320 IP Phone VoIP phone,2017-06-09,2017-06-14,Standard Class,Brosina Hoffman,Consumer,United States,Los Angeles,California,West
8,CA-2017-115812,BH-11710,90032,OFF-BI-10003910,18.504,3,0.2,5.7825,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,2017-06-09,2017-06-14,Standard Class,Brosina Hoffman,Consumer,United States,Los Angeles,California,West

# Sort Values

In [ ]:
# ascending = True
df.sort_values('sales').head()

,order_id,customer_id,postal_code,product_id,sales,quantity,discount,profit,category,sub-category,product_name,order_date,ship_date,ship_mode,customer_name,segment,country/region,city,state,region
4101,US-2020-102288,ZC-21910,77095,OFF-AP-10002906,0.444,1,0.8,-1.1100,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,2020-06-19,2020-06-23,Standard Class,Zuschuss Carroll,Consumer,United States,Houston,Texas,Central
9292,CA-2020-124114,RS-19765,76706,OFF-BI-10004022,0.556,1,0.8,-0.9452,Office Supplies,Binders,Acco Suede Grain Vinyl Round Ring Binder,2020-03-02,2020-03-02,Same Day,Roland Schwarz,Corporate,United States,Waco,Texas,Central
8658,CA-2019-168361,KB-16600,60623,OFF-BI-10003727,0.836,1,0.8,-1.3376,Office Supplies,Binders,Avery Durable Slant Ring Binders With Label Ho...,2019-06-21,2019-06-25,Standard Class,Ken Brennan,Corporate,United States,Chicago,Illinois,Central
4711,CA-2017-112403,JO-15280,19120,OFF-BI-10003529,0.852,1,0.7,-0.5964,Office Supplies,Binders,Avery Round Ring Poly Binders,2017-03-31,2017-03-31,Same Day,Jas O'Carroll,Consumer,United States,Philadelphia,Pennsylvania,East
2106,US-2017-152723,HG-14965,75150,OFF-BI-10003460,0.876,1,0.8,-1.4016,Office Supplies,Binders,Acco 3-Hole Punch,2017-09-26,2017-09-26,Same Day,Henry Goldwyn,Corporate,United States,Mesquite,Texas,Central

In [ ]:
# ascending = False
# cara mengisi argumen:
  # 1. Positional Argument
  # 2. Keyword Argument
df.sort_values('sales', ascending=False).head()

,order_id,customer_id,postal_code,product_id,sales,quantity,discount,profit,category,sub-category,product_name,order_date,ship_date,ship_mode,customer_name,segment,country/region,city,state,region
2697,CA-2017-145317,SM-20320,32216,TEC-MA-10002412,22638.480,6,0.5,-1811.0784,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,2017-03-18,2017-03-23,Standard Class,Sean Miller,Home Office,United States,Jacksonville,Florida,South
6826,CA-2019-118689,TC-20980,47905,TEC-CO-10004722,17499.950,5,0.0,8399.9760,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,2019-10-02,2019-10-09,Standard Class,Tamara Chand,Corporate,United States,Lafayette,Indiana,Central
8153,CA-2020-140151,RB-19360,98115,TEC-CO-10004722,13999.960,4,0.0,6719.9808,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,2020-03-23,2020-03-25,First Class,Raymond Buch,Consumer,United States,Seattle,Washington,West
2623,CA-2020-127180,TA-21385,10024,TEC-CO-10004722,11199.968,4,0.2,3919.9888,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,2020-10-22,2020-10-24,First Class,Tom Ashbrook,Home Office,United States,New York City,New York,East
4190,CA-2020-166709,HL-15040,19711,TEC-CO-10004722,10499.970,3,0.0,5039.9856,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,2020-11-17,2020-11-22,Standard Class,Hunter Lopez,Consumer,United States,Newark,Delaware,East

In [ ]:
def pengurangan(x, y):
  return x - y

In [ ]:
# positional argument
pengurangan(2, 1)

1

In [ ]:
# positional argument
pengurangan(1, 2)

-1

In [ ]:
# keyword argument
pengurangan(y=1, x=2)

1

In [ ]:
# keyword vs positional
pengurangan(2, y=1)

1

## Sorting more than 1 column

In [ ]:
df.sort_values(['sales', 'quantity'], ascending=[True, False]).head()

,order_id,customer_id,postal_code,product_id,sales,quantity,discount,profit,category,sub-category,product_name,order_date,ship_date,ship_mode,customer_name,segment,country/region,city,state,region
4101,US-2020-102288,ZC-21910,77095,OFF-AP-10002906,0.444,1,0.8,-1.1100,Office Supplies,Appliances,Hoover Replacement Belt for Commercial Guardsm...,2020-06-19,2020-06-23,Standard Class,Zuschuss Carroll,Consumer,United States,Houston,Texas,Central
9292,CA-2020-124114,RS-19765,76706,OFF-BI-10004022,0.556,1,0.8,-0.9452,Office Supplies,Binders,Acco Suede Grain Vinyl Round Ring Binder,2020-03-02,2020-03-02,Same Day,Roland Schwarz,Corporate,United States,Waco,Texas,Central
8658,CA-2019-168361,KB-16600,60623,OFF-BI-10003727,0.836,1,0.8,-1.3376,Office Supplies,Binders,Avery Durable Slant Ring Binders With Label Ho...,2019-06-21,2019-06-25,Standard Class,Ken Brennan,Corporate,United States,Chicago,Illinois,Central
4711,CA-2017-112403,JO-15280,19120,OFF-BI-10003529,0.852,1,0.7,-0.5964,Office Supplies,Binders,Avery Round Ring Poly Binders,2017-03-31,2017-03-31,Same Day,Jas O'Carroll,Consumer,United States,Philadelphia,Pennsylvania,East
2106,US-2017-152723,HG-14965,75150,OFF-BI-10003460,0.876,1,0.8,-1.4016,Office Supplies,Binders,Acco 3-Hole Punch,2017-09-26,2017-09-26,Same Day,Henry Goldwyn,Corporate,United States,Mesquite,Texas,Central

# Descriptive Analysis

In [ ]:
df.describe()

,sales,quantity,discount,profit,order_date,ship_date
count,9994.000000,9994.000000,9994.000000,9994.000000,9994,9994
mean,229.858001,3.789574,0.156203,28.656896,2019-04-30 17:41:20.448268800,2019-05-04 16:42:15.921553152
min,0.444000,1.000000,0.000000,-6599.978000,2017-01-03 00:00:00,2017-01-07 00:00:00
25%,17.280000,2.000000,0.000000,1.728750,2018-05-23 00:00:00,2018-05-27 00:00:00
50%,54.490000,3.000000,0.200000,8.666500,2019-06-26 00:00:00,2019-06-29 00:00:00
75%,209.940000,5.000000,0.200000,29.364000,2020-05-14 00:00:00,2020-05-18 00:00:00
max,22638.480000,14.000000,0.800000,8399.976000,2020-12-30 00:00:00,2021-01-05 00:00:00
std,623.245101,2.225110,0.206452,234.260108,NaN,NaN

In [ ]:
df.describe(include='object')

,order_id,customer_id,product_id,category,sub-category,product_name,ship_mode,customer_name,segment,country/region,city,state,region
count,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994,9994
unique,5009,793,1862,3,17,1817,4,793,3,1,531,49,4
top,CA-2020-100111,WB-21850,OFF-PA-10001970,Office Supplies,Binders,Staple envelope,Standard Class,William Brown,Consumer,United States,New York City,California,West
freq,14,37,19,6026,1523,48,5968,37,5191,9994,915,2001,3203

# Value Counts

In [ ]:
df['region'].value_counts()

region
West       3203
East       2848
Central    2323
South      1620
Name: count, dtype: int64

In [ ]:
np.round(df['region'].value_counts(normalize=True)*100, 2)

region
West       32.05
East       28.50
Central    23.24
South      16.21
Name: proportion, dtype: float64

# Sumarizing Data

In [ ]:
df

,order_id,customer_id,postal_code,product_id,sales,quantity,discount,profit,category,sub-category,product_name,order_date,ship_date,ship_mode,customer_name,segment,country/region,city,state,region
0,CA-2019-152156,CG-12520,42420,FUR-BO-10001798,261.9600,2,0.00,41.9136,Furniture,Bookcases,Bush Somerset Collection Bookcase,2019-11-08,2019-11-11,Second Class,Claire Gute,Consumer,United States,Henderson,Kentucky,South
1,CA-2019-152156,CG-12520,42420,FUR-CH-10000454,731.9400,3,0.00,219.5820,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",2019-11-08,2019-11-11,Second Class,Claire Gute,Consumer,United States,Henderson,Kentucky,South
2,CA-2019-138688,DV-13045,90036,OFF-LA-10000240,14.6200,2,0.00,6.8714,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,2019-06-12,2019-06-16,Second Class,Darrin Van Huff,Corporate,United States,Los Angeles,California,West
3,US-2018-108966,SO-20335,33311,FUR-TA-10000577,957.5775,5,0.45,-383.0310,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,2018-10-11,2018-10-18,Standard Class,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,South
4,US-2018-108966,SO-20335,33311,OFF-ST-10000760,22.3680,2,0.20,2.5164,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,2018-10-11,2018-10-18,Standard Class,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,South
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,CA-2017-110422,TB-21400,33180,FUR-FU-10001889,25.2480,3,0.20,4.1028,Furniture,Furnishings,Ultra Door Pull Handle,2017-01-21,2017-01-23,Second Class,Tom Boeckenhauer,Consumer,United States,Miami,Florida,South
9990,CA-2020-121258,DB-13060,92627,FUR-FU-10000747,91.9600,2,0.00,15.6332,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,2020-02-26,2020-03-03,Standard Class,Dave Brooks,Consumer,United States,Costa Mesa,California,West
9991,CA-2020-121258,DB-13060,92627,TEC-PH-10003645,258.5760,2,0.20,19.3932,Technology,Phones,Aastra 57i VoIP phone,2020-02-26,2020-03-03,Standard Class,Dave Brooks,Consumer,United States,Costa Mesa,California,West
9992,CA-2020-121258,DB-13060,92627,OFF-PA-10004041,29.6000,4,0.00,13.3200,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",2020-02-26,2020-03-03,Standard Class,Dave Brooks,Consumer,United States,Costa Mesa,California,West
9993,CA-2020-119914,CC-12220,92683,OFF-AP-10002684,243.1600,2,0.00,72.9480,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",2020-05-04,2020-05-09,Second Class,Chris Cortes,Consumer,United States,Westminster,California,West

In [ ]:
sumarize_df = df.groupby(['order_date', 'region', 'category']).agg({'sales': 'sum', 'quantity': 'sum'})
sumarize_df

                                       sales  quantity
order_date region  category
2017-01-03 Central Office Supplies    16.448         2
2017-01-04 Central Office Supplies   288.060         8
2017-01-05 East    Office Supplies    19.536         3
2017-01-06 South   Furniture        2573.820         9
                   Office Supplies   665.900        12
...                                      ...       ...
2020-12-30 Central Office Supplies   209.300         2
           East    Furniture         323.136         4
                   Office Supplies    52.776         3
                   Technology         90.930         7
           West    Office Supplies    37.648         7

[5175 rows x 2 columns]

In [ ]:
sumarize_df[['sales', 'quantity']]

                                       sales  quantity
order_date region  category
2017-01-03 Central Office Supplies    16.448         2
2017-01-04 Central Office Supplies   288.060         8
2017-01-05 East    Office Supplies    19.536         3
2017-01-06 South   Furniture        2573.820         9
                   Office Supplies   665.900        12
...                                      ...       ...
2020-12-30 Central Office Supplies   209.300         2
           East    Furniture         323.136         4
                   Office Supplies    52.776         3
                   Technology         90.930         7
           West    Office Supplies    37.648         7

[5175 rows x 2 columns]

In [ ]:
sumarize_df.reset_index(inplace=True)

In [ ]:
sumarize_df

     order_date   region         category     sales  quantity
0    2017-01-03  Central  Office Supplies    16.448         2
1    2017-01-04  Central  Office Supplies   288.060         8
2    2017-01-05     East  Office Supplies    19.536         3
3    2017-01-06    South        Furniture  2573.820         9
4    2017-01-06    South  Office Supplies   665.900        12
...         ...      ...              ...       ...       ...
5170 2020-12-30  Central  Office Supplies   209.300         2
5171 2020-12-30     East        Furniture   323.136         4
5172 2020-12-30     East  Office Supplies    52.776         3
5173 2020-12-30     East       Technology    90.930         7
5174 2020-12-30     West  Office Supplies    37.648         7

[5175 rows x 5 columns]